// mockData.ts
// Mock rikishi data for testing the bout engine
//
// FIXES:
// - No Math.random() (keeps determinism)
// - Imports aligned to your updated types
// - Avoids relying on initializeEconomics signature quirks
// - Adds missing required fields safely (rankNumber only where needed)
// - Deterministic helpers accept seed

import seedrandom from "seedrandom";
import type { Rikishi, TacticalArchetype, RikishiEconomics, Rank } from "./types";
import { initializeEconomics } from "./economics";

// Helper to create economics with custom values
function createEconomics(overrides: Partial<RikishiEconomics> = {}): RikishiEconomics {
  return { ...initializeEconomics(), ...overrides };
}

// Helper: ensure rankNumber only for numbered ranks
function maybeRankNumber(rank: Rank, n?: number): number | undefined {
  if (rank === "maegashira" || rank === "juryo" || rank === "makushita" || rank === "sandanme" || rank === "jonidan" || rank === "jonokuchi") {
    return n;
  }
  return undefined;
}

// Sample rikishi with tactical archetypes and economics
export const SAMPLE_RIKISHI: Rikishi[] = [
  {
    id: "hakuryu",
    shikona: "Hakuryū",
    realName: "Tanaka Ichiro",
    heyaId: "miyagino",
    nationality: "Japan",
    height: 192,
    weight: 158,
    power: 88,
    speed: 72,
    balance: 85,
    technique: 90,
    aggression: 78,
    experience: 95,
    momentum: 5,
    stamina: 100,
    injured: false,
    injuryWeeksRemaining: 0,
    style: "yotsu",
    archetype: "yotsu_specialist",
    division: "makuuchi",
    rank: "yokozuna",
    rankNumber: maybeRankNumber("yokozuna"),
    side: "east",
    careerWins: 1045,
    careerLosses: 198,
    currentBashoWins: 0,
    currentBashoLosses: 0,
    favoredKimarite: ["yorikiri", "uwatenage", "shitatenage"],
    weakAgainstStyles: [],
    economics: createEconomics({
      retirementFund: 180_000_000,
      careerKenshoWon: 2450,
      kinboshiCount: 0,
      totalEarnings: 320_000_000,
      popularity: 95,
      currentBashoEarnings: 0,
    }),
  },
  {
    id: "kaiou",
    shikona: "Kaiō",
    realName: "Suzuki Daisuke",
    heyaId: "tomozuna",
    nationality: "Japan",
    height: 185,
    weight: 175,
    power: 92,
    speed: 65,
    balance: 80,
    technique: 82,
    aggression: 85,
    experience: 88,
    momentum: 2,
    stamina: 100,
    injured: false,
    injuryWeeksRemaining: 0,
    style: "oshi",
    archetype: "oshi_specialist",
    division: "makuuchi",
    rank: "ozeki",
    rankNumber: maybeRankNumber("ozeki"),
    side: "west",
    careerWins: 756,
    careerLosses: 312,
    currentBashoWins: 0,
    currentBashoLosses: 0,
    favoredKimarite: ["oshidashi", "tsukidashi", "oshitaoshi"],
    weakAgainstStyles: ["yotsu"],
    economics: createEconomics({
      retirementFund: 85_000_000,
      careerKenshoWon: 1120,
      kinboshiCount: 0,
      totalEarnings: 145_000_000,
      popularity: 78,
      currentBashoEarnings: 0,
    }),
  },
  {
    id: "wakatora",
    shikona: "Wakatora",
    realName: "Yamamoto Kenji",
    heyaId: "kasugano",
    nationality: "Japan",
    height: 178,
    weight: 145,
    power: 70,
    speed: 88,
    balance: 82,
    technique: 75,
    aggression: 90,
    experience: 55,
    momentum: 8,
    stamina: 100,
    injured: false,
    injuryWeeksRemaining: 0,
    style: "hybrid",
    archetype: "speedster",
    division: "makuuchi",
    rank: "sekiwake",
    rankNumber: maybeRankNumber("sekiwake"),
    side: "east",
    careerWins: 312,
    careerLosses: 178,
    currentBashoWins: 0,
    currentBashoLosses: 0,
    favoredKimarite: ["hatakikomi", "ketaguri", "okuridashi"],
    weakAgainstStyles: [],
    economics: createEconomics({
      retirementFund: 25_000_000,
      careerKenshoWon: 380,
      kinboshiCount: 2,
      totalEarnings: 48_000_000,
      popularity: 72,
      currentBashoEarnings: 0,
    }),
  },
  {
    id: "takanofuji",
    shikona: "Takanofuji",
    realName: "Ito Masahiro",
    heyaId: "takanohana",
    nationality: "Japan",
    height: 188,
    weight: 162,
    power: 82,
    speed: 75,
    balance: 88,
    technique: 85,
    aggression: 72,
    experience: 78,
    momentum: 0,
    stamina: 100,
    injured: false,
    injuryWeeksRemaining: 0,
    style: "yotsu",
    archetype: "all_rounder",
    division: "makuuchi",
    rank: "komusubi",
    rankNumber: maybeRankNumber("komusubi"),
    side: "west",
    careerWins: 445,
    careerLosses: 289,
    currentBashoWins: 0,
    currentBashoLosses: 0,
    favoredKimarite: ["yorikiri", "kotenage", "sotogake"],
    weakAgainstStyles: ["oshi"],
    economics: createEconomics({
      retirementFund: 35_000_000,
      careerKenshoWon: 520,
      kinboshiCount: 1,
      totalEarnings: 62_000_000,
      popularity: 58,
      currentBashoEarnings: 0,
    }),
  },
  {
    id: "tochinoshin",
    shikona: "Tochinoshin",
    realName: "Levan Gorgadze",
    heyaId: "kasugano",
    nationality: "Georgia",
    height: 192,
    weight: 177,
    power: 95,
    speed: 58,
    balance: 75,
    technique: 78,
    aggression: 80,
    experience: 82,
    momentum: -3,
    stamina: 85,
    injured: false,
    injuryWeeksRemaining: 0,
    style: "yotsu",
    archetype: "yotsu_specialist",
    division: "makuuchi",
    rank: "maegashira",
    rankNumber: maybeRankNumber("maegashira", 1),
    side: "east",
    careerWins: 567,
    careerLosses: 423,
    currentBashoWins: 0,
    currentBashoLosses: 0,
    favoredKimarite: ["tsuridashi", "yorikiri", "uwatenage"],
    weakAgainstStyles: [],
    economics: createEconomics({
      retirementFund: 55_000_000,
      careerKenshoWon: 780,
      kinboshiCount: 3,
      totalEarnings: 95_000_000,
      popularity: 82,
      currentBashoEarnings: 0,
    }),
  },
  {
    id: "enho",
    shikona: "Enhō",
    realName: "Yuki Nakamura",
    heyaId: "miyagino",
    nationality: "Japan",
    height: 168,
    weight: 99,
    power: 45,
    speed: 95,
    balance: 90,
    technique: 88,
    aggression: 75,
    experience: 60,
    momentum: 4,
    stamina: 100,
    injured: false,
    injuryWeeksRemaining: 0,
    style: "hybrid",
    archetype: "trickster",
    division: "makuuchi",
    rank: "maegashira",
    rankNumber: maybeRankNumber("maegashira", 8),
    side: "west",
    careerWins: 234,
    careerLosses: 187,
    currentBashoWins: 0,
    currentBashoLosses: 0,
    favoredKimarite: ["hatakikomi", "ketaguri", "katasukashi", "izori"],
    weakAgainstStyles: [],
    economics: createEconomics({
      retirementFund: 18_000_000,
      careerKenshoWon: 290,
      kinboshiCount: 4,
      totalEarnings: 32_000_000,
      popularity: 88, // fan favorite
      currentBashoEarnings: 0,
    }),
  },
  {
    id: "asanoyama",
    shikona: "Asanoyama",
    realName: "Hiroki Ishibashi",
    heyaId: "takasago",
    nationality: "Japan",
    height: 187,
    weight: 160,
    power: 80,
    speed: 70,
    balance: 84,
    technique: 82,
    aggression: 70,
    experience: 72,
    momentum: 3,
    stamina: 100,
    injured: false,
    injuryWeeksRemaining: 0,
    style: "yotsu",
    archetype: "all_rounder",
    division: "makuuchi",
    rank: "maegashira",
    rankNumber: maybeRankNumber("maegashira", 2),
    side: "east",
    careerWins: 398,
    careerLosses: 267,
    currentBashoWins: 0,
    currentBashoLosses: 0,
    favoredKimarite: ["yorikiri", "uwatenage", "sukuinage"],
    weakAgainstStyles: [],
    economics: createEconomics({
      retirementFund: 28_000_000,
      careerKenshoWon: 410,
      kinboshiCount: 2,
      totalEarnings: 52_000_000,
      popularity: 65,
      currentBashoEarnings: 0,
    }),
  },
  {
    id: "takakeisho",
    shikona: "Takakeishō",
    realName: "Takayuki Sato",
    heyaId: "chiganoura",
    nationality: "Japan",
    height: 175,
    weight: 170,
    power: 90,
    speed: 72,
    balance: 78,
    technique: 75,
    aggression: 92,
    experience: 80,
    momentum: 6,
    stamina: 95,
    injured: false,
    injuryWeeksRemaining: 0,
    style: "oshi",
    archetype: "oshi_specialist",
    division: "makuuchi",
    rank: "ozeki",
    rankNumber: maybeRankNumber("ozeki"),
    side: "east",
    careerWins: 512,
    careerLosses: 298,
    currentBashoWins: 0,
    currentBashoLosses: 0,
    favoredKimarite: ["oshidashi", "tsukidashi", "hatakikomi"],
    weakAgainstStyles: ["yotsu"],
    economics: createEconomics({
      retirementFund: 72_000_000,
      careerKenshoWon: 980,
      kinboshiCount: 0,
      totalEarnings: 125_000_000,
      popularity: 75,
      currentBashoEarnings: 0,
    }),
  },
];

export function getRikishiById(id: string): Rikishi | undefined {
  return SAMPLE_RIKISHI.find(r => r.id === id);
}

/**
 * Deterministic pair (no Math.random).
 * Use a seed you control, e.g. `getRandomRikishiPair(world.seed + "-test")`
 */
export function getRandomRikishiPair(seed: string = "mock-pair"): [Rikishi, Rikishi] {
  const rng = seedrandom(seed);
  const idxA = Math.floor(rng() * SAMPLE_RIKISHI.length);

  // ensure different
  let idxB = Math.floor(rng() * (SAMPLE_RIKISHI.length - 1));
  if (idxB >= idxA) idxB += 1;

  return [SAMPLE_RIKISHI[idxA], SAMPLE_RIKISHI[idxB]];
}

// Get rikishi by archetype for testing
export function getRikishiByArchetype(archetype: TacticalArchetype): Rikishi[] {
  return SAMPLE_RIKISHI.filter(r => r.archetype === archetype);
}
